language: node_js  #设置语言

node_js: 8  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cp CNAME ./public
  - cp README.md ./public
  - cd ./public
  - git init
  - git config user.name "Zeven"  #修改name
  - git config user.email "zevenfang@users.noreply.github.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
  - git push --force --quiet "https://${CODING_USER}:${CODING_PASS}@${CODING_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/ZevenFang/zevenfang.github.io.git
   - CODING_REF: e.coding.net/zeven/zeven.coding.me.git
